### ISSUE TITLE
Multi server install

### ISSUE THREAD

**Issue by black-gull** [Zimbra-Community/zimbra-foss-2fa#30]
Hi, I'm following your guide for a multiserver installation (a standalone Zimbra server and a stand alone 2fa server).

I notice a communication problem between the Zimbra standalone server (for example, named zimbraserver) and the local service (inside the docker) on port 1389 of a server of different IP (the 2fa standalone server).
In particular, I refer to the command in point 9 of the guide:

ldapsearch -x -H ldap://172.18.0.2:1389 -D uid=user2,ou=people,dc=zimbradev,dc=barrydegraaff,dc=tk -w "PASSWORD HERE***OTP HERE***" "mail=*"

and the command:

curl -d "user=user1&pass=testabc944412" -X POST http://172.18.0.2:8000/validate/check

Obviously, zimbraserver cannot communicate directly with the services (tcp/1389, tcp/8000) exposed by 172.18.0.2.

How to resolve?

Thanks and congratulations for the great work!
Diego

**Comment by barrydegraaff** [comment]
I remember that I added a docker network so that both privacyIdea and the ldap proxy could be on known ip's. But this is an issue if you split stuff over multiple servers.

One option would be to remove the network and see if you can make that work:

 Instead of using:

       docker run --init --net zimbradocker --ip 172.18.0.2 -p 5000:443 --name privacyidea --restart=always -v privacyidea_data:/etc/privacyidea -v privacyidea_log:/var/log/privacyidea -v privacyidea_mariadb:/var/lib/mysql -v /opt/privacyIdeaLDAPProxy:/opt/privacyIdeaLDAPProxy -d zetalliance/privacy-idea:latest

use something like 

        docker run --init  -p 5000:443 -p 8000:8000 --name privacyidea --restart=always -v privacyidea_data:/etc/privacyidea -v privacyidea_log:/var/log/privacyidea -v privacyidea_mariadb:/var/lib/mysql -v /opt/privacyIdeaLDAPProxy:/opt/privacyIdeaLDAPProxy -d zetalliance/privacy-idea:latest

**BE ADVISED by removing the network argument from docker run you will expose port 5000 and 8000 and docker WILL CIRCUMVENT iptables so make sure to check from where port 5000/8000 can be accessed!** 

https://docs.docker.com/config/containers/container-networking/

So the trick is also to use -p 8000:8000, that will expose the LDAP proxy. It has been a while since I looked into this, so you will have to do some research to get it done.

**Comment by black-gull** [comment]
Hi Barry, thanks for the quick reply!
I believe the tcp /1389 port should also be exposed.
Maybe with:
docker run --init  -p 5000:443 -p 8000:8000 -p 1389:1389 .........................
Is it correct ?
The guide specifies the URL for external authentication: ldap://172.18.0.2:1389.

Thank's,
Diego

**Comment by barrydegraaff** [comment]
yes, but look at the dockerfile and all
config files to find out what else needs to be updated.
